apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-lanchonete  # Defina o namespace desejado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/app-lanchonete:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"  # Defina os limites de CPU conforme necessário
              memory: "128Mi"  # Defina os limites de memória conforme necessário
            requests:
              cpu: "0.25"  # Defina as solicitações de CPU conforme necessário
              memory: "128Mi"  # Defina as solicitações de memória conforme necessário
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app-lanchonete  # Defina o namespace desejado
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-lanchonete  # Defina o namespace desejado
spec:
  rules:
    - host: app-lanchonete.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minha-app
                port:
                  number: 80
